[package]
name = "jobfire-ephemeral"
version = "0.1.0"
edition = "2024"

[dependencies]
jobfire-core.workspace = true
chrono.workspace = true
serde.workspace = true
tokio.workspace = true
uuid.workspace = true
thiserror.workspace = true
log.workspace = true
