[package]
name = "jobfire-example-simple"
version = "0.1.0"
edition = "2024"

[dependencies]
jobfire-core.workspace = true
jobfire-storage-in-memory.workspace = true
log.workspace = true
simple_logger.workspace = true
chrono.workspace = true
tokio.workspace = true
serde.workspace = true
